dependencies:
  pre:
    - wget http://download.redis.io/releases/redis-3.2.0.tar.gz
    - tar xzf redis-3.2.0.tar.gz
    - cd redis-3.2.0 && make
  cache_directories:
    - redis-3.2.0

test:
  pre:
    - sudo service redis-server stop
    - ./redis-3.2.0/src/redis-server --port 6391 --daemonize yes

  override:
    - cd packages/server; yarn test
